### ISSUE TITLE
Support non-sudo installation

### ISSUE THREAD

**Issue by ObiWahn** [maks-a/batterym#1]
» ./uninstall.sh 
cat: install_log.txt: No such file or directory

**Comment by maks-a** [comment]
Have you tried `sudo ./uninstall.sh`?

`install_log.txt` must be in the same folder as `uninstall.sh`.

**Comment by ObiWahn** [comment]
I have installed it with the --user flag. What should be the location of the install_log.txt?

**Comment by maks-a** [comment]
`install_log.txt` should appear in the same folder as `install.sh`, but it does not happen because non-sudo installation is not supported.
I'll rename this issue to support non-sudo installation.

**Comment by maks-a** [comment]
Possible solution for non-sudo installation issue is committed to ['non_sudo' branch](https://github.com/maks-a/batterym/commits/non_sudo). Please test it, if it's OK I'll merge it to master branch.

**Comment by maks-a** [comment]
'non_sudo' branch is merged into master.
Done.
