### ISSUE TITLE
Uninstall script doesn't remove directories

### ISSUE THREAD

**Issue by yermulnik** [maks-a/batterym#21]
Looks like `uninstall.sh` script only removes files and not directories. So there's a bunch of battrym dirs left around after uninstallation.

**Comment by maks-a** [comment]
Acknowledged.

**Comment by maks-a** [comment]
Imporvements up to [this commit](https://github.com/maks-a/batterym/commit/6680e4cf16e8bb567fe325c64498119740a0f2a9):
- `~/.local/batterym/` is removed after installation. The only one that is left for now is `~/.local/lib/python2.7/site-packages/batterym`, I don't know how to fix it yet
- added verbose mode for files/folders removal during uninstallation
- added (un)install final message, like `batterym is successfully (un)installed`

**Comment by maks-a** [comment]
@yermulnik: any suggestions how to remove `~/.local/lib/python2.7/site-packages/batterym` ?

**Comment by yermulnik** [comment]
I don't know =( Guess for now you'll have to live it as is.

Anyway I'd suggest to add `set -e` to `uninstall.sh` file after shebang line to fail immediately if `rm` fails (to not echo successful uninstallation if it was not):
```
--- uninstall.sh.orig   2017-04-17 01:42:59.251289929 +0300
+++ uninstall.sh        2017-04-17 01:43:03.863289835 +0300
@@ -1,3 +1,4 @@
 #!/bin/sh
+set -e
 cat install_log.txt | xargs rm -rfv
 echo 'batterym is successfully uninstalled.'
```

**Comment by maks-a** [comment]
Added `set -e` to (un)install.sh. I close this issue for now, feel free to re-open.

@yermulnik: thank you for help!
